"""empty message

Revision ID: 7914661f6633
Revises: c55709239741
Create Date: 2018-12-24 11:01:47.504941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7914661f6633'
down_revision = 'c55709239741'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('signature', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'signature')
    # ### end Alembic commands ###
